// <auto-generated />
using System;
using EFCoreConsoleApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreConsoleApp.Migrations
{
    [DbContext(typeof(BillingContext))]
    [Migration("20240516142004_ChangeBillAndContract")]
    partial class ChangeBillAndContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreConsoleApp.Models.BillingTransaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("billingTimestamp")
                        .HasColumnType("int");

                    b.Property<string>("customerToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<string>("doctorToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("failureBPMAPICount")
                        .HasColumnType("int");

                    b.Property<int>("failureClassificationAPICount")
                        .HasColumnType("int");

                    b.Property<int>("failureRecognitionAPICount")
                        .HasColumnType("int");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<string>("partnerToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("successBPMAPICount")
                        .HasColumnType("int");

                    b.Property<int>("successClassificationAPICount")
                        .HasColumnType("int");

                    b.Property<string>("transactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("userToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("BillTransactions");
                });

            modelBuilder.Entity("EFCoreConsoleApp.Models.Contract", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("contractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("contractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("contractStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("downpayment")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("downpaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("partnerToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("subscriptionPlanId")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.HasIndex("partnerToken")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("EFCoreConsoleApp.Models.MonthlyBilling", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("failureCount")
                        .HasColumnType("int");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<string>("partnerToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("subscriptionPlanId")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<int>("successCount")
                        .HasColumnType("int");

                    b.Property<decimal>("thereafter")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("year", "month", "partnerToken")
                        .IsUnique();

                    b.ToTable("MonthlyBillings");
                });

            modelBuilder.Entity("EFCoreConsoleApp.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("billingPricingPerMonth")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("maxTransactionsPerMonth")
                        .HasColumnType("int");

                    b.Property<string>("subscriptionPlanId")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<decimal>("thereafterAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("tierName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("SubscriptionPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
